cl/opinion_page/urls.py
from cl.opinion_page.sitemap import opinion_sitemap_maker
from cl.opinion_page.views import (
    view_opinion, view_authorities, view_docket, cluster_visualizations,
    citation_redirector
)
from django.conf.urls import url


urlpatterns = [
    url(
        r'^opinion/(?P<pk>\d*)/(?P<slug>[^/]*)/authorities/$',
        view_authorities,
        name='view_authorities'
    ),
    url(
        r'^opinion/(?P<pk>\d*)/(?P<slug>[^/]*)/visualizations/$',
        cluster_visualizations,
        name='cluster_visualizations',
    ),
    url(
        r'^opinion/(\d*)/([^/]*)/$',
        view_opinion,
        name="view_case"
    ),
    url(
        r'^docket/(\d*)/([^/]*)/$',
        view_docket,
        name="view_docket"
    ),
    url(
        r'^c/(?:(?P<reporter>.*)/(?P<volume>\d{1,4})/(?P<page>\d{1,4})/)?$',
        citation_redirector,
        name="citation_redirector",
    ),

    # Sitemap
    url(
        r'^sitemap-opinions\.xml',
        opinion_sitemap_maker,
        name='opinion_sitemap',
    ),
]

cl/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from cl.opinion_page.views import (
    redirect_opinion_pages, redirect_cited_by_feeds,
    redirect_cited_by_page)
#from cl.simple_pages.views import show_maintenance_warning
from cl.sitemap import index_sitemap_maker

urlpatterns = [
    # Admin docs and site
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # Maintenance and SOPA/PIPA mode! Must be here so it intercepts any other
    # urls.
    #url(r'/*', show_maintenance_warning),

    url('', include('cl.audio.urls')),
    url('', include('cl.opinion_page.urls')),
    url('', include('cl.simple_pages.urls')),
    url('', include('cl.users.urls')),
    url('', include('cl.favorites.urls')),
    url('', include('cl.people_db.urls')),
    url('', include('cl.search.urls')),
    url('', include('cl.alerts.urls')),
    url('', include('cl.api.urls')),
    url('', include('cl.donate.urls')),
    url('', include('cl.visualizations.urls')),

    # Sitemaps
    url(r'^sitemap\.xml$', index_sitemap_maker),

    # Redirects
    url(r'^privacy/$', RedirectView.as_view(
        url='/terms/#privacy',
        permanent=True,
    )),
    url(r'^removal/$', RedirectView.as_view(
        url='/terms/#removal',
        permanent=True,
    )),
    url(r'^report/2010/$', RedirectView.as_view(
        url='https://www.ischool.berkeley.edu/files/student_projects/Final_Report_Michael_Lissner_2010-05-07_2.pdf',
        permanent=True,
    )),
    url(r'^report/2012/$', RedirectView.as_view(
        url='https://www.ischool.berkeley.edu/files/student_projects/mcdonald_rustad_report.pdf',
        permanent=True,
    )),
    url(r'report/2013/$', RedirectView.as_view(
        url='https://github.com/freelawproject/related-literature/raw/master/CourtListener%20Studies/Sarah%20Tyler/sarah_tyler_dissertation.pdf',
        permanent=True,
    )),

    # Court stripped from the URL on 2014-09-30.
    # cited-by pages and feeds moved to search results on 2015-08-25
    url(r'^feed/(.*)/cited-by/$', redirect_cited_by_feeds),
    # catch the formats:
    #    /$court/$ascii/$slug/cited-by/ and
    #    /$opinion/$number/$slug/cited-by/
    url(r'^(?:\w{1,15})/(.*)/(?:.*)/cited-by/$', redirect_cited_by_page),
    url(r'^(?:\w{1,15})/(.*)/(.*)/authorities/$', redirect_opinion_pages),
    url(r'^(?:\w{1,15})/(.*)/(.*)/$', redirect_opinion_pages),
]

cl/audio/models.py
from cl.people_db.models import Person
from cl.lib.model_helpers import make_upload_path
from cl.lib.storage import IncrementingFileSystemStorage
from cl.search.models import Docket, SOURCES

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models


class Audio(models.Model):
    """A class representing oral arguments and their associated metadata

    """
    docket = models.ForeignKey(
        Docket,
        help_text="The docket that the oral argument is a part of",
        related_name="audio_files",
        blank=True,
        null=True,
    )
    source = models.CharField(
        help_text="the source of the audio file, one of: %s" %
                  ', '.join(['%s (%s)' % (t[0], t[1]) for t in SOURCES]),
        max_length=10,
        choices=SOURCES,
        blank=True,
    )
    case_name_short = models.TextField(
        help_text="The abridged name of the case, often a single word, e.g. "
                  "'Marsh'",
        blank=True,
    )
    case_name = models.TextField(
        help_text="The full name of the case",
        blank=True,
    )
    case_name_full = models.TextField(
        help_text="The full name of the case",
        blank=True
    )
    panel = models.ManyToManyField(
        Person,
        help_text="The judges that heard the oral arguments",
        related_name="oral_argument_panel_members",
        blank=True,
    )
    judges = models.TextField(
        help_text="The judges that heard the oral arguments as a simple text "
                  "string. This field is used when normalized judges cannot "
                  "be placed into the panel field.",
        blank=True,
        null=True,
    )
    date_created = models.DateTimeField(
        help_text="The original creation date for the item",
        auto_now_add=True,
        db_index=True,
    )
    date_modified = models.DateTimeField(
        help_text="The last moment when the item was modified. A value in year"
                  " 1750 indicates the value is unknown",
        auto_now=True,
        db_index=True,
    )
    sha1 = models.CharField(
        help_text="unique ID for the document, as generated via SHA1 of the "
                  "binary file or text data",
        max_length=40,
        db_index=True,
    )
    download_url = models.URLField(
        help_text="The URL on the court website where the document was "
                  "originally scraped",
        max_length=500,
        db_index=True,
        null=True,
        blank=True,
    )
    local_path_mp3 = models.FileField(
        help_text="The location, relative to MEDIA_ROOT, on the CourtListener "
                  "server, where encoded file is stored",
        upload_to=make_upload_path,
        storage=IncrementingFileSystemStorage(),
        blank=True,
        db_index=True,
    )
    local_path_original_file = models.FileField(
        help_text="The location, relative to MEDIA_ROOT, on the CourtListener "
                  "server, where the original file is stored",
        upload_to=make_upload_path,
        storage=IncrementingFileSystemStorage(),
        db_index=True,
    )
    duration = models.SmallIntegerField(
        help_text="the length of the item, in seconds",
        null=True,
    )
    processing_complete = models.BooleanField(
        help_text="Is audio for this item done processing?",
        default=False,
    )
    date_blocked = models.DateField(
        help_text="The date that this opinion was blocked from indexing by "
                  "search engines",
        blank=True,
        null=True,
        db_index=True,
    )
    blocked = models.BooleanField(
        help_text="Should this item be blocked from indexing by "
                  "search engines?",
        db_index=True,
        default=False,
    )

    class Meta:
        ordering = ["-date_created"]
        verbose_name_plural = 'Audio Files'

    def __unicode__(self):
        return u'%s: %s' % (self.pk, self.case_name)

    def get_absolute_url(self):
        return reverse('view_audio_file', args=[self.pk, self.docket.slug])

    def save(self, index=True, force_commit=False, *args, **kwargs):
        """
        Overrides the normal save method, but provides integration with the
        bulk files and with Solr indexing.

        :param index: Should the item be added to the Solr index?
        :param commit: Should a commit be performed after adding it?
        """
        super(Audio, self).save(*args, **kwargs)
        if index:
            from cl.search.tasks import add_or_update_audio_files
            add_or_update_audio_files.delay([self.pk], force_commit)

    def delete(self, *args, **kwargs):
        """
        Update the index as items are deleted.
        """
        id_cache = self.pk
        super(Audio, self).delete(*args, **kwargs)
        from cl.search.tasks import delete_items
        delete_items.delay([id_cache], settings.SOLR_AUDIO_URL)

cl/opinion_page/forms.py
from django import forms


class CitationRedirectorForm(forms.Form):
    volume = forms.IntegerField(
        widget=forms.TextInput(attrs={
            'class': 'form-control input-lg',
            'placeholder': 'Volume',
        }),
        required=True,
    )
    reporter = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control input-lg',
            'placeholder': 'Reporter',
        }),
        required=True,
    )
    page = forms.IntegerField(
        widget=forms.TextInput(attrs={
            'class': 'form-control input-lg',
            'placeholder': 'Page',
        }),
        required=True,
    )

cl/opinion_page/templates/citation_redirect_info_page.html
{% extends "base.html" %}
{% load text_filters %}

{% block sidebar %}{% endblock %}
{% block search-form %}{% endblock %}


{% block title %}
    {% if show_homepage %}
        Citation Lookup Tool – CourtListener.com
    {% else %}
        {% if none_found %}
            Citation Not Found (404) – CourtListener.com
        {% elif too_many %}
            Several Citations Found – CourtListener.com
        {% endif %}
    {% endif %}
{% endblock %}


{% block content %}
    {% if show_homepage %}
        <div class="hidden-sm hidden-xs col-md-1 col-lg-2"></div>
        <div class="col-xs-12 col-md-10 col-lg-8">
            <h2>Citation Lookup Tool</h2>

            <p>If you have a citation you want to look up, put it in here, and
                we'll look it up.</p>

            {% if form.errors %}
                <div class="alert alert-danger">
                    <p class="bottom">Error: All fields are required.</p>
                </div>
            {% endif %}

            <form action="" method="post">{% csrf_token %}
                <div class="form-inline">
                    <div class="form-group">
                        <label class="sr-only" for="id_volume">Volume</label>
                        {{ form.volume }}
                    </div>
                    <div class="form-group">
                        <label class="sr-only" for="id_reporter">Reporter</label>
                        {{ form.reporter }}
                    </div>
                    <div class="form-group">
                        <label class="sr-only" for="id_page">Page</label>
                        {{ form.page }}
                    </div>
                    <button type="submit" class="btn btn-lg btn-primary">Look It Up</button>
                </div>
            </form>

            <h3 class="v-offset-above-4">About this Tool</h3>
            <p>This tool generates URLs so that you can easily look up a citation that you know. If you're a person that prefers to just hack URLs, you can do that too, using a URL like <code>{% url "citation_redirector" volume="410" reporter="U.S." page="113" %}</code>, which will take you straight to <em>Roe v. Wade</em>. Or you can always just come here and type in a citation that you know.
            </p>
            <p>This tool can handle a lot of different reporters as defined in our <a href="https://github.com/freelawproject/reporters-db" target="_blank">Reporter Database</a>. For example, the <em>United States Reports</em> has historically been abbreviated as either "U.S.S.C.Rep." or "USSCR". Our system knows these are equivalent and either will work.
            </p>
            <p>Sometimes a citation is not unique because multiple opinions were on the same page in a reporter. When this happens, you will be given a list of opinions to choose from.
            </p>
            <p>It almost goes without saying, but this tool is limited by the citations that we have in our system. As we improve our collection and add citations to opinions that we have, this tool will automatically work for those opinions as well.
            </p>
            <p>You can <a href="https://free.law/2015/11/30/our-new-citation-finder/" target="_blank">read more about this tool</a> on our blog.</p>
        </div>
        <div class="hidden-sm hidden-xs col-md-1 col-lg-2"></div>
    {% else %}
        <div class="col-md-3"></div>
        <div class="col-md-6" id="citation-redirect">
            {% if none_found %}
                <h2>Unable to Find Citation "{{ citation_str }}"</h2>
                <p>This usually happens because although we might have an opinion in
                    CourtListener, we might lack its official citation or an
                    official parallel citation.
                </p>
                <p>In most jurisdictions, citations are unavailable at the time of
                    publication, making this a particularly thorny problem.
                </p>
            {% elif too_many %}
                <h2 class="v-offset-below-2">Found More than One Result for "{{ citation_str }}"</h2>
                <ul>
                    {% for cluster in clusters %}
                        <li>
                            <a href="{{ cluster.get_absolute_url }}">{{ cluster.caption|safe|v_wrapper }}</a>
                            <br>
                            {{ cluster.docket.court }} |
                            {{ cluster.date_filed }}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="col-md-3"></div>
    {% endif %}
{% endblock %}

cl/opinion_page/templates/view_docket.html
{% extends "base.html" %}
{% load text_filters %}
{% load humanize %}
{% load admin_urls %}

{% block title %}Docket for {{ docket|best_case_name }} –
    CourtListener.com{% endblock %}
{% block og_title %}Docket for {{ docket|best_case_name }} -
    CourtListener.com{% endblock %}
{% block description %}Docket for {{ docket|best_case_name }}{% endblock %}
{% block og_description %}Docket for {{ docket|best_case_name }}{% endblock %}

{% block sidebar %}
    <div class="col-sm-3" id="sidebar">
      {% if request.user.is_superuser %}
        <div class="sidebar-section">
          {% if private %}
          <div class="btn btn-danger btn-xs">Blocked from Search Engines</div>
          {% endif %}
        </div>
      {% endif %}
    </div>
{% endblock sidebar %}

{% block content %}
    <div class="col-xs-12">
        {% if perms.search.change_docket %}
            <p class="float-right">
                <a href="{% url 'admin:search_docket_change' docket.id %}"
                   class="btn btn-primary btn-xs">Edit&nbsp;Docket&nbsp;<i
                   class="fa fa-pencil"></i>
                </a>
            </p>
        {% endif %}
        <h2>{{ docket|best_case_name|safe|v_wrapper }}</h2>

        {% if docket.clusters.count %}
        <div>
            <h3>There {% if docket.clusters.count == 1 %}is{% else %}are{% endif %} {{ docket.clusters.count|apnumber|intcomma }} opinion{{ docket.clusters.count|pluralize }} associated with this docket.</h3>
            <hr>
            <ul>
                {% for cluster in docket.clusters.all %}
                    <li>
                        <a href="{{ cluster.get_absolute_url }}?{{ request.META.QUERY_STRING }}">
                            {{ cluster.caption|safe|v_wrapper }}
                        </a>
                        {% if perms.search.change_document %}
                            <a href="{% url 'admin:search_opinioncluster_change' cluster.pk %}"
                               class="btn btn-primary btn-xs">Edit</a>
                        {% endif %}
                        <br/>
                        {{ cluster.date_filed }}
                    </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        {% if docket.audio_files.count %}
        <div>
            <h3>There {% if docket.audio_files.count == 1 %}is{% else %}are{% endif %} {{ docket.audio_files.count|apnumber|intcomma }} audio file{{ docket.audio_files.count|pluralize }} on this docket.</h3>
            <hr>
            <ul>
                {% for af in docket.audio_files.all %}
                    <li>
                        <a href="{{ af.get_absolute_url }}?{{ request.META.QUERY_STRING }}">
                            {{ af|best_case_name|safe|v_wrapper }}
                        </a>
                        {% if perms.audio.change_audio %}
                            <a href="{% url 'admin:audio_audio_change' af.pk %}"
                               class="btn btn-primary btn-xs">Edit</a>
                        {% endif %}
                        <br/>
                        {{ af.docket.date_argued }}
                    </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>
{% endblock %}

cl/opinion_page/templates/view_opinion.html
{% extends "base.html" %}
{% load text_filters %}

{% block title %}{{ title }} – CourtListener.com{% endblock %}
{% block og_title %}{{ title }} – CourtListener.com{% endblock %}
{% block description %}Opinion for {{ title }}{% endblock %}
{% block og_description %}Opinion for {{ title }}{% endblock %}
{% block search-form %}{% endblock %}

{% block head %}
    <link rel="alternate" type="application/rss+xml" title="Atom feed for cases citing {{cluster|best_case_name|truncatewords:10}}" href="/feed/search/?q=cites:({{ cluster.sub_opinions.all|OR_join }})">
{% endblock %}

{% block footer-scripts %}
    <script defer type="text/javascript" src="{{ STATIC_URL }}js/jquery.NobleCount.min.js"></script>
    <script defer type="text/javascript" src="{{ STATIC_URL }}js/save-favorites.js"></script>
{% endblock %}

{% block sidebar %}
    <div class="col-sm-3" id="sidebar">
        <div class="sidebar-section">
            <h4>
                <i class="fa fa-arrow-circle-o-left gray"></i>
                <a href="/?{{ request.META.QUERY_STRING }}">Back to {% if get_string %}Search Results{% else %}Home Page{% endif %}</a>
            </h4>
        </div>

        {# show the admin tools if applicable #}
        {% if perms.search.change_docket or perms.search.change_opinioncluster or perms.search.change_citation %}
            <div class="sidebar-section">
                <h3><span>Admin</span></h3>
                <p>
                    {% if perms.search.change_docket %}
                        <a href="{% url 'admin:search_docket_change' cluster.docket.pk %}"
                           class="btn btn-primary btn-xs">Docket</a>
                    {% endif %}
                    {% if perms.search.change_opinioncluster %}
                        <a href="{% url 'admin:search_opinioncluster_change' cluster.pk %}"
                           class="btn btn-primary btn-xs">Cluster</a>
                    {% endif %}
                    {% if perms.search.change_opinion %}
                        {% for sub_opinion in cluster.sub_opinions.all|dictsort:"type" %}
                            <a href="{% url 'admin:search_opinion_change' sub_opinion.pk %}"
                               class="btn btn-primary btn-xs">{{ sub_opinion.type }} opinion</a>
                        {% endfor %}
                    {% endif %}
                    {% if request.user.is_superuser %}
                      {% if private %}
                      <div class="btn btn-danger btn-xs">Blocked from Search Engines</div>
                      {% endif %}
                    {% endif %}
                </p>
            </div>
        {% endif %}

        {# show this div if it is a favorite, otherwise, put it in place, in anticipation of it becoming one. #}
        <div class="{% if not favorite_form.instance.cluster_id %}hidden{% endif %} sidebar-section" id="sidebar-notes">
            <div>
                <h3 class="inline"><span>Your Notes</span></h3>
                <p class="inline" data-toggle="modal" data-target="#modal-save-favorite">
                    (<a href="#favorite-editor">edit</a>)
                     <i class="fa fa-pencil gray pointer"></i>
                </p>
                <p id="sidebar-notes-text">
                    {{ favorite_form.instance.notes|default:"(none)" }}
                </p>
            </div>
        </div>

        {# Show cases that cite this case #}
        {% if citing_clusters.result.numFound > 0 %}
            <div id="cited-by" class="sidebar-section">
                <h3><span>Cited By ({{ citing_clusters.result.numFound }})</span></h3>
                <p class="bottom">This case has been cited by these opinions:</p>
                <ul>
                    {% for citing_cluster in citing_clusters %}
                        <li>
                            <a href="{{ citing_cluster.absolute_url }}?{{ request.META.QUERY_STRING }}">{{ citing_cluster.caseName|safe|truncatewords:12|v_wrapper }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <h4>
                    <a href="/?q=cites%3A({{ cluster.sub_opinions.all|OR_join }})"
                       class="btn btn-default">
                        View All Citing Opinions
                    </a>
                </h4>
            </div>
        {% endif %}

        {# Show cases this case cites #}
        {% if top_authorities %}
            <div id="authorities" class="sidebar-section">
                <h3><span>Authorities ({{ cluster.authority_count }})</span></h3>
                <p class="bottom">This opinion cites:</p>
                <ul>
                    {% for authority in top_authorities %}
                        <li>
                            <a href="{{ authority.get_absolute_url }}?{{ request.META.QUERY_STRING }}">
                                {{ authority.caption|safe|truncatewords:10|v_wrapper }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
                <h4>
                    <a href="{% url "view_authorities" pk=cluster.pk slug=cluster.slug %}?{{ request.META.QUERY_STRING }}"
                       class="btn btn-default">
                        View All Authorities
                    </a>
                </h4>
            </div>
        {% endif %}

        {# Visualizations #}
        {% if cluster.top_visualizations %}
            <div id="visualizations" class="sidebar-section">
                <h3><span>Visualizations</span></h3>
                <ul>
                    {% for viz in cluster.top_visualizations|slice:":5" %}
                        <li>
                            <a href="{{ viz.get_absolute_url }}">
                                {{ viz.title|truncatewords:10 }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
                <h4>
                    <a href="{% url "cluster_visualizations" pk=cluster.pk slug=cluster.slug %}?{{ request.META.QUERY_STRING }}"
                       class="btn btn-default">
                        View Full List
                    </a>
                    <a href="{% url "new_visualization" %}"
                       class="btn btn-success">
                        <i class="fa fa-plus"></i>&nbsp;New Network</a>
                </h4>
            </div>
        {% endif %}

        {# Download original? #}
        {% for sub_opinion in cluster.sub_opinions.all|dictsort:"type" %}
            {% if sub_opinion.download_url or sub_opinion.local_path %}
                <div class="sidebar-section">
                    {% if sub_opinion.source != 'R' and sub_opinion.source != 'L' and sub_opinion.source != 'LR' %}
                        <h3><span>Original {{sub_opinion.get_type_display}}</span></h3>
                        <p>
                            {% if sub_opinion.download_url and sub_opinion.source != 'R' %}
                                <a href="{{sub_opinion.download_url}}" class="visitable">From the court</a>
                            {% endif %}
                            {% if sub_opinion.download_url and sub_opinion.source != 'R' and sub_opinion.local_path %}
                                &nbsp;&nbsp;|&nbsp;&nbsp;
                            {% endif %}
                            {% if sub_opinion.local_path %}
                                <a href="/{{sub_opinion.local_path}}" class="visitable">Our backup</a>
                            {% endif %}
                        </p>
                    {% endif %}
                </div>
            {% endif %}
        {% endfor %}

        {% include "includes/social_links.html" %}
        {% include "includes/donate_sidebar.html" with referrer="ad-o" %}
    </div>
{% endblock %}


{% block content %}
    <article class="col-sm-9">
        <i id="favorites-star"
           class="{% if favorite_form.instance.cluster_id %}gold fa-star{% else %}gray fa-star-o bold{% endif %} pointer fa inline"
           data-toggle="modal"
           data-target="#modal-save-favorite, #modal-logged-out"
           title="Save this record as a favorite in your profile"></i>
        <h2 class="inline">{{ cluster.caption|safe|v_wrapper }}</h2>
        {% include "includes/favorites_modal.html" %}

        <h3>{{ cluster.docket.court }}</h3>
        <p class="bottom">
            <span class="meta-data-header">Filed:</span>
            <span class="meta-data-value">
                {{cluster.date_filed|date:"F jS, Y"}}
            </span>
        </p>
        <p class="bottom">
            <span class="meta-data-header">Precedential Status:</span>
            <span class="meta-data-value">
                {{cluster.get_precedential_status_display|default:'Unknown'}}
            </span>
        </p>
        <p class="bottom">
            <span class="meta-data-header">Citations:</span>
            <span class="meta-data-value">
                {{ cluster.citation_string|default:"None known" }}
            </span>
        </p>
        <p class="bottom">
            <span class="meta-data-header">Docket Number:</span>
            <span class="meta-data-value">
                {{ cluster.docket.docket_number|default:"Unknown" }}
            </span>
        </p>
        {% if cluster.docket.court_id == 'scotus' %}
        <p class="bottom">
            <span class="meta-data-header">Supreme Court Database ID:</span>
            <span class="meta-data-value">
                {% if cluster.scdb_id %}
                    <a href="http://supremecourtdatabase.org/analysisCaseDetail.php?cid={{ cluster.scdb_id }}" target="_blank">
                    {{ cluster.scdb_id }}
                    </a><i class="gray fa fa-external-link"></i>
                {% else %}
                    Unknown
                {% endif %}
            </span>
        </p>
        {% endif %}
        <p class="bottom">
            <span class="meta-data-header">Judges:</span>
            <span class="meta-data-value">
                {{ cluster.judges|default:"Unknown" }}
            </span>
        </p>
        <p class="bottom">
            <span class="meta-data-header">Nature of suit:</span>
            <span class="meta-data-value">
                {{ cluster.nature_of_suit|default:"Unknown" }}
            </span>
        </p>
        <br>

        {# Only display tabs and make panels if more than one sub-opinion. #}
        {% with opinion_count=cluster.sub_opinions.all.count %}
            {% if opinion_count > 1 %}
                <ul class="nav nav-tabs v-offset-below-3" role="tablist">
                    {% for sub_opinion in cluster.sub_opinions.all|dictsort:"type" %}
                        <li role="presentation" {% if forloop.first %}class="active"{% endif %}>
                            <a href="#{{ sub_opinion.type }}{{ forloop.counter }}"
                               aria-controls="{{ sub_opinion.type }}{{ forloop.counter }}"
                               role="tab"
                               data-toggle="tab">{{ sub_opinion.get_type_display }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}

            <div class="tab-content">
                {% for sub_opinion in cluster.sub_opinions.all|dictsort:"type" %}
                    <div {% if opinion_count > 1 %}
                            role="tabpanel"
                            class="tab-pane {% if forloop.first %}active{% endif %}"
                        {% endif %}
                            id="{{ sub_opinion.type }}{{ forloop.counter }}">

                        {% if sub_opinion.extracted_by_ocr %}
                            <div class="col-sm-12 alert-warning alert">
                                <p class="bottom">The text of this document was
                                    obtained by analyzing a scanned document
                                    provided by the court. As a result it may have
                                    typos, and you may prefer <a
                                            href="{{ sub_opinion.download_url }}"
                                            class="visitable">reading the
                                        original</a>.
                                </p>
                            </div>
                            <div class="clearfix"></div>
                        {% endif %}
                        {% if 'Z' in cluster.source %}
                        <div id="columbia-text">
                        {% elif 'L' in cluster.source %}
                        <div id='lawbox-text'>
                        {% elif 'R' in cluster.source %}
                        <div id='resource-org-text'>
                        {% else %}
                        <div id='default-text'>
                        {% endif %}
                            <div id="opinion-content"> {# used by Zotero, Juris-M #}
                                {% if sub_opinion.html_with_citations %}
                                    {{ sub_opinion.html_with_citations|safe }}
                                {% elif sub_opinion.html_columbia %}
                                    {{ sub_opinion.html_columbia|safe }}
                                {% elif sub_opinion.html_lawbox %}
                                    {{ sub_opinion.html_lawbox|safe }}
                                {% elif sub_opinion.html %}
                                    {{sub_opinion.html|safe}}
                                {% else %}
                                    <pre>{{sub_opinion.plain_text}}</pre>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endwith %}
    </article>
{% endblock %}