cl/simple_pages/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from cl.simple_pages.sitemap import sitemap_maker
from cl.simple_pages.views import (
    tools_page, validate_for_google, validate_for_google2, validate_for_wot,
    validate_for_bing, robots, advanced_search, contact_thanks, contact, feeds,
    coverage_graph, faq, about, browser_warning, serve_static_file, old_terms,
    latest_terms, contribute, markdown_help, humans,
)

mime_types = ('pdf', 'wpd', 'txt', 'doc', 'html', 'mp3')


urlpatterns = [
    # Footer stuff
    url(r'^about/$', about, name='about'),
    url(r'^faq/$', faq, name="faq"),
    url(r'^coverage/$', coverage_graph, name='coverage'),
    url(r'^feeds/$', feeds, name='feeds_info'),
    url(r'^contribute/$', contribute, name='contribute'),
    url(r'^contact/$', contact, name="contact"),
    url(r'^contact/thanks/$', contact_thanks, name='contact_thanks'),
    url(r'^help/markdown/$', markdown_help, name="markdown_help"),

    # Serve a static file
    url(r'^(?P<file_path>(?:' + "|".join(mime_types) + ')/.*)$',
        serve_static_file),

    # Advanced search page
    url(
        r'^search/advanced-techniques/$',
        advanced_search,
        name='advanced_search'
    ),

    url(r'^terms/v/(\d{1,2})/$', old_terms, name='old_terms'),
    url(r'^terms/$', latest_terms, name='terms'),

    # Randoms
    url(
        r'^tools/$',
        tools_page,
        name='tools',
    ),
    url(
        r'^bad-browser/$',
        browser_warning,
        name='bad_browser',
    ),

    # Robots & Humans
    url(
        r'^robots\.txt$',
        robots,
        name='robots'
    ),
    url(
        r'^humans\.txt$',
        humans,
        name='humans',
    ),

    # Sitemap:
    url(
        r'^sitemap-simple-pages\.xml$',
        sitemap_maker,
        name='simple_pages_sitemap',
    ),

    # SEO-related stuff
    url(r'^BingSiteAuth.xml$', validate_for_bing),
    url(r'^googleef3d845637ccb353.html$', validate_for_google),
    url(r'^google646349975c2495b6.html$', validate_for_google2),
    url(r'^mywot8f5568174e171ff0acff.html$', validate_for_wot),

    # Favicon, touch icons, etc.
    url(r'^favicon\.ico$',
        RedirectView.as_view(
            url='/static/ico/favicon.ico',
            permanent=True)),
    url(r'^touch-icon-192x192\.png',
        RedirectView.as_view(
            url='/static/png/touch-icon-192x192.png',
            permanent=True)),
    url(r'^apple-touch-icon\.png$',
        RedirectView.as_view(
            url='/static/png/apple-touch-icon.png',
            permanent=True)),
    url(r'^apple-touch-icon-72x72-precomposed\.png$',
        RedirectView.as_view(
            url='/static/png/apple-touch-icon-72x72-precomposed.png',
            permanent=True)),
    url(r'^apple-touch-icon-76x76-precomposed\.png$',
        RedirectView.as_view(
            url='/static/png/apple-touch-icon-76x76-precomposed.png',
            permanent=True)),
    url(r'^apple-touch-icon-114x114-precomposed\.png$',
        RedirectView.as_view(
            url='/static/png/apple-touch-icon-114x114-precomposed.png',
            permanent=True)),
    url(r'^apple-touch-icon-120x120-precomposed\.png$',
        RedirectView.as_view(
            url='/static/png/apple-touch-icon-120x120-precomposed.png',
            permanent=True)),
    url(r'^apple-touch-icon-144x144-precomposed\.png$',
        RedirectView.as_view(
            url='/static/png/apple-touch-icon-144x144-precomposed.png',
            permanent=True)),
    url(r'^apple-touch-icon-152x152-precomposed\.png$',
        RedirectView.as_view(
            url='/static/png/apple-touch-icon-152x152-precomposed.png',
            permanent=True)),
    url(r'^apple-touch-icon-180x180-precomposed\.png$',
        RedirectView.as_view(
            url='/static/png/apple-touch-icon-180x180-precomposed.png',
            permanent=True)),
    url(r'^apple-touch-icon-precomposed\.png$',
        RedirectView.as_view(
            url='/static/png/apple-touch-icon-precomposed.png',
            permanent=True)),
]

cl/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from cl.opinion_page.views import (
    redirect_opinion_pages, redirect_cited_by_feeds,
    redirect_cited_by_page)
#from cl.simple_pages.views import show_maintenance_warning
from cl.sitemap import index_sitemap_maker

urlpatterns = [
    # Admin docs and site
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # Maintenance and SOPA/PIPA mode! Must be here so it intercepts any other
    # urls.
    #url(r'/*', show_maintenance_warning),

    url('', include('cl.audio.urls')),
    url('', include('cl.opinion_page.urls')),
    url('', include('cl.simple_pages.urls')),
    url('', include('cl.users.urls')),
    url('', include('cl.favorites.urls')),
    url('', include('cl.people_db.urls')),
    url('', include('cl.search.urls')),
    url('', include('cl.alerts.urls')),
    url('', include('cl.api.urls')),
    url('', include('cl.donate.urls')),
    url('', include('cl.visualizations.urls')),

    # Sitemaps
    url(r'^sitemap\.xml$', index_sitemap_maker),

    # Redirects
    url(r'^privacy/$', RedirectView.as_view(
        url='/terms/#privacy',
        permanent=True,
    )),
    url(r'^removal/$', RedirectView.as_view(
        url='/terms/#removal',
        permanent=True,
    )),
    url(r'^report/2010/$', RedirectView.as_view(
        url='https://www.ischool.berkeley.edu/files/student_projects/Final_Report_Michael_Lissner_2010-05-07_2.pdf',
        permanent=True,
    )),
    url(r'^report/2012/$', RedirectView.as_view(
        url='https://www.ischool.berkeley.edu/files/student_projects/mcdonald_rustad_report.pdf',
        permanent=True,
    )),
    url(r'report/2013/$', RedirectView.as_view(
        url='https://github.com/freelawproject/related-literature/raw/master/CourtListener%20Studies/Sarah%20Tyler/sarah_tyler_dissertation.pdf',
        permanent=True,
    )),

    # Court stripped from the URL on 2014-09-30.
    # cited-by pages and feeds moved to search results on 2015-08-25
    url(r'^feed/(.*)/cited-by/$', redirect_cited_by_feeds),
    # catch the formats:
    #    /$court/$ascii/$slug/cited-by/ and
    #    /$opinion/$number/$slug/cited-by/
    url(r'^(?:\w{1,15})/(.*)/(?:.*)/cited-by/$', redirect_cited_by_page),
    url(r'^(?:\w{1,15})/(.*)/(.*)/authorities/$', redirect_opinion_pages),
    url(r'^(?:\w{1,15})/(.*)/(.*)/$', redirect_opinion_pages),
]

cl/simple_pages/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )

    email = forms.EmailField(
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )

    subject = forms.CharField(
        max_length=150,
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )

    message = forms.CharField(
        min_length=20,
        widget=forms.Textarea(
            attrs={'class': 'form-control'}
        )
    )

cl/simple_pages/views.py
import json
import os

from django.conf import settings
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.db.models import Count
from django.http import HttpResponseRedirect, Http404
from django.http import HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.template import loader
from django.views.decorators.cache import cache_page, never_cache

from cl.audio.models import Audio
from cl.custom_filters.decorators import check_honeypot
from cl.lib import magic
from cl.lib import search_utils
from cl.lib.bot_detector import is_bot
from cl.lib.sunburnt import sunburnt
from cl.search.models import Court, OpinionCluster, Opinion
from cl.search.forms import SearchForm
from cl.simple_pages.forms import ContactForm
from cl.stats import tally_stat


def about(request):
    """Loads the about page"""
    return render_to_response(
        'about.html',
        {'private': False},
        RequestContext(request)
    )


def faq(request):
    """Loads the FAQ page"""
    scraped_court_count = Court.objects.filter(
        in_use=True,
        has_opinion_scraper=True
    ).count()
    conn = sunburnt.SolrInterface(settings.SOLR_OPINION_URL, mode='r')
    response = conn.raw_query(
        **search_utils.build_total_count_query()).execute()
    total_opinion_count = response.result.numFound
    return contact(
        request,
        template_path='faq.html',
        template_data={
            'scraped_court_count': scraped_court_count,
            'total_opinion_count': total_opinion_count,
        },
        initial={'subject': 'FAQs'},
    )


def markdown_help(request):
    return render_to_response(
        'markdown_help.html',
        {'private': False},
        RequestContext(request),
    )


def build_court_dicts(courts):
    """Takes the court objects, and manipulates them into a list of more useful
    dictionaries"""
    court_dicts = [{'pk': 'all',
                    'short_name': u'All Courts'}]
    court_dicts.extend([{'pk': court.pk,
                         'short_name': court.full_name, }
                        #'notes': court.notes}
                        for court in courts])
    return court_dicts


def coverage_graph(request):
    courts = Court.objects.filter(in_use=True)
    courts_json = json.dumps(build_court_dicts(courts))

    search_form = SearchForm(request.GET)
    precedential_statuses = [field for field in
        search_form.fields.keys() if field.startswith('stat_')]

    # Build up the sourcing stats.
    counts = OpinionCluster.objects.values('source').annotate(Count('source'))
    count_pro = 0
    count_lawbox = 0
    count_scraper = 0
    for d in counts:
        if 'R' in d['source']:
            count_pro += d['source__count']
        if 'C' in d['source']:
            count_scraper += d['source__count']
        if 'L' in d['source']:
            count_lawbox += d['source__count']

    opinion_courts = Court.objects.filter(
        in_use=True,
        has_opinion_scraper=True)
    oral_argument_courts = Court.objects.filter(
        in_use=True,
        has_oral_argument_scraper=True)
    return render_to_response(
        'coverage_graph.html',
        {
            'sorted_courts': courts_json,
            'precedential_statuses': precedential_statuses,
            'count_pro': count_pro,
            'count_lawbox': count_lawbox,
            'count_scraper': count_scraper,
            'courts_with_opinion_scrapers': opinion_courts,
            'courts_with_oral_argument_scrapers': oral_argument_courts,
            'private': False
        },
        RequestContext(request))


def feeds(request):
    opinion_courts = Court.objects.filter(
        in_use=True,
        has_opinion_scraper=True
    )
    oral_argument_courts = Court.objects.filter(
        in_use=True,
        has_oral_argument_scraper=True
    )
    return render_to_response(
        'feeds.html',
        {
            'opinion_courts': opinion_courts,
            'oral_argument_courts': oral_argument_courts,
            'private': False
        },
        RequestContext(request)
    )


def contribute(request):
    return render_to_response(
        'contribute.html',
        {'private': False},
        RequestContext(request),
    )


@check_honeypot(field_name='skip_me_if_alive')
def contact(
        request,
        template_path='contact_form.html',
        template_data=None,
        initial=None):
    """This is a fairly run-of-the-mill contact form, except that it can be
    overridden in various ways so that its logic can be called from other
    functions.
    """
    if template_data is None:
        template_data = {}
    if initial is None:
        initial = {}

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            default_from = settings.DEFAULT_FROM_EMAIL
            EmailMessage(
                subject=u'[CourtListener] Contact form message',
                body=u'Subject: {subject}\n'
                     u'From: {name} ({email})\n'
                     u'Browser: {browser}\n'
                     u'Message: \n\n{message}'.format(
                        browser=request.META.get(u'HTTP_USER_AGENT', u"Unknown"),
                        **cd
                     ),
                to=[m[1] for m in settings.MANAGERS],
                reply_to=[cd.get(u'email', default_from) or default_from],
            ).send()
            return HttpResponseRedirect(reverse(u'contact_thanks'))
    else:
        # the form is loading for the first time
        try:
            initial[u'email'] = request.user.email
            initial[u'name'] = request.user.get_full_name()
            form = ContactForm(initial=initial)
        except AttributeError:
            # for anonymous users, who lack full_names, and emails
            form = ContactForm(initial=initial)

    template_data.update(
        {u'form': form,
         u'private': False}
    )
    return render_to_response(
        template_path,
        template_data,
        RequestContext(request)
    )


def contact_thanks(request):
    return render_to_response(
        u'contact_thanks.html',
        {u'private': True},
        RequestContext(request)
    )


def advanced_search(request):
    return render_to_response(
        'advanced_search.html',
        {'private': False},
        RequestContext(request)
    )


def old_terms(request, v):
    return render_to_response(
        'terms/%s.html' % v,
        {
            'title': 'Archived Terms of Service and Policies, v%s - CourtListener.com' % v,
            'private': True
        },
        RequestContext(request),
    )


def latest_terms(request):
    return render_to_response(
        'terms/latest.html',
        {
            'title': 'Terms of Service and Policies - CourtListener.com',
            'private': False
        },
        RequestContext(request),
    )


@never_cache
def show_maintenance_warning(request):
    """Blocks access to a URL, and instead loads a maintenance warning.

    Uses a 503 status code, which preserves SEO. See:
    https://plus.google.com/115984868678744352358/posts/Gas8vjZ5fmB
    """
    return render_to_response(
        'maintenance.html',
        {'private': True},
        RequestContext(request),
        status=503,  # Temporarily Unavailable
    )


@cache_page(60 * 60 * 12)  # 12 hours
def robots(request):
    """Generate the robots.txt file"""
    response = HttpResponse(content_type='text/plain')
    t = loader.get_template('robots.txt')
    response.write(t.render({}))
    return response


@cache_page(60 * 60 * 12)  # 12 hours
def humans(request):
    """Generate the humans.txt file"""
    response = HttpResponse(content_type='text/plain')
    t = loader.get_template('humans.txt')
    response.write(t.render({}))
    return response


def validate_for_bing(request):
    return HttpResponse('<?xml version="1.0"?><users><user>8BA95D8EAA744379D80D9F70847EA156</user></users>')


def validate_for_google(request):
    return HttpResponse('google-site-verification: googleef3d845637ccb353.html')


def validate_for_google2(request):
    return HttpResponse('google-site-verification: google646349975c2495b6.html')


def validate_for_wot(request):
    return HttpResponse('bcb982d1e23b7091d5cf4e46826c8fc0')


def tools_page(request):
    return render_to_response(
        'tools.html',
        {'private': False},
        RequestContext(request)
    )


def browser_warning(request):
    return render_to_response(
        'browser_warning.html',
        {'private': True},
        RequestContext(request)
    )


def serve_static_file(request, file_path=''):
    """Sends a static file to a user.

    This serves up the static case files such as the PDFs in a way that can be
    blocked from search engines if necessary. We do four things:
     - Look up the document  or audio file associated with the filepath
     - Check if it's blocked
     - If blocked, we set the x-robots-tag HTTP header
     - Serve up the file using Apache2's xsendfile
    """
    response = HttpResponse()
    file_loc = os.path.join(settings.MEDIA_ROOT, file_path.encode('utf-8'))
    if file_path.startswith('mp3'):
        item = get_object_or_404(Audio, local_path_mp3=file_path)
        mimetype = 'audio/mpeg'
    else:
        item = get_object_or_404(Opinion, local_path=file_path)
        item.blocked = item.cluster.blocked
        try:
            mimetype = magic.from_file(file_loc, mime=True)
        except IOError:
            raise Http404

    if item.blocked:
        response['X-Robots-Tag'] = 'noindex, noodp, noarchive, noimageindex'

    if settings.DEVELOPMENT:
        # X-Sendfile will only confuse you in a dev env.
        response.content = open(file_loc, 'r').read()
    else:
        response['X-Sendfile'] = file_loc

cl/simple_pages/templates/about.html
{% extends "base.html" %}

{% block title %}About – CourtListener.com{% endblock %}
{% block search-form %}{% endblock %}
{% block sidebar %}{% endblock %}

{% block content %}
    <div class="col-sm-5">
        <h2 id="the-site">About</h2>

        <p>Started in 2010, CourtListener is a core project of the <a
                href="https://free.law/">Free Law Project</a>, a
            federally-recognized 501(c)(3) public charity and a
            California non-profit public benefit corporation. Free Law
            Project seeks to provide free access to primary legal materials,
            develop legal research tools, and support academic research on
            legal corpora. CourtListener embodies all of these efforts, as the
            primary free repository of all the court opinions we have
            collected, as the platform on which we deploy legal research tools,
            and as the source of bulk downloads that enable academic
            researchers to study our collection.
        </p>

        <p>We collect legal opinions from court websites and from data
            donations, and are aiming to have the best, most complete data on
            the open Web within the next couple years. We are slowly expanding
            to provide search and awareness tools for as many state courts as
            possible, and we already have tools for all of the Federal Appeals
            Courts. For more details on which jurisdictions we support see our
            <a href="{% url "coverage" %}">coverage page</a>. If you're able to help us
            acquire more cases, please <a href="{% url "contact" %}">get in touch</a>.
        </p>

        <h3 id="contribute">You Make CourtListener.</h3>
        <p>CourtListener is a community project and we enthusiastically welcome
            contributions. There are many ways to contribute, which are
            detailed on our <a href="{% url "contribute" %}">contribute page</a>.

        <p>We are thankful for the hard work of our past contributors:</p>
        <ul>
            <li>Jason Aller for his work to make CourtListener mobile-friendly
                and for his enhancements to the <a href="{% url "coverage" %}">
                    coverage page
                </a>.
            </li>
            <li>Karen Rustad &amp; Rowyn McDonald for creating our citator,
                cross-linker and coverage graphs.</li>
            <li>Bo Jin (Krist) for creating the heart of our relevance
                engine.</li>
            <li>Josh de-Larios Heiman for his pro-bono legal expertise.</li>
            <li>Siddharth Agrawal &amp; Andrew McConachie for their research on
                keyword identification.</li>
            <li>Sarah Tyler for her research into search relevance and user
                interfaces.</li>
            <li>Peter Nguyen for his design work for the jurisdiction
                picker.</li>
            <li>Ben Cassidy, Commetric, Inc., Bo Jin (Krist), Deb Linton,
                Matt Meiske, Andrew McConachie, Taliah B. Mirmalek, David
                Zvenyach for their work on the Juriscraper scraper framework.
            </li>
        </ul>
        <p>We've also had generous support from a handful of organizations
            including (in alphabetical order):
            <a href="http://casetext.com">CaseText</a>,
            <a href="http://www.fastcase.com">FastCase</a>,
            <a href="http://justia">Justia</a>,
            <a href="http://lawboxapps.com/">Lawbox, Inc.</a>,
            <a href="https://plainsite.org">PlainSite</a>, and
            <a href="https://public.resource.org">Public.Resource.Org</a>.
        </p>
    </div>

    <div class="col-sm-7">
        <h2 id="Team">Team</h2>
        <div class="media">
            <div class="media-left media-object">
                <img class="headshot"
                     src="{{ STATIC_URL }}jpeg/brian.jpeg"
                     height="270" width="270"
                     alt="Photo of Brian W. Carver">
            </div>
            <div class="media-body">
                <h3 class="media-heading">Brian W. Carver</h3>
                <p>Brian W. Carver is the Co-Founder of the non-profit <a
                        href="https://free.law">Free Law Project</a>,
                    and an Assistant Professor at the <a
                            href="http://ischool.berkeley.edu">University of
                        California, Berkeley School of Information</a>. He
                    researches and teaches about intellectual property law and
                    cyberlaw and is also engaged in efforts to increase the
                    public's access to the law.
                </p>
            </div>
        </div>

        <div class="media">
            <div class="media-left media-object">
                <img class="headshot"
                     src="{{ STATIC_URL }}jpeg/mike.jpeg"
                     height="270" width="270"
                     alt="Photo of Michael Lissner">
            </div>
            <div class="media-body">
                <h3 class="media-heading">Michael Lissner</h3>
                <p>Michael Lissner is the Lead Developer and Co-Founder of the
                    non-profit <a href="https://free.law">Free Law
                        Project</a>. Before founding Free Law Project, he
                    spent several years working in the enterprise search and
                    e-discovery fields, building bespoke search systems. He is
                    a graduate of the <a
                            href="http://ischool.berkeley.edu">University of
                        California, Berkeley School of Information</a> and a
                    long-distance walker, crossing both the <a
                            href="http://pcta.org">United States</a> and <a
                            href="http://www.teararoa.org.nz/">New Zealand</a>
                    on foot.
                </p>
            </div>
        </div>
    </div>
{% endblock %}

cl/simple_pages/templates/browser_warning.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/override.css" type="text/css" media="screen, projection">
    <title>Please Update Your Browser</title>
</head>
<body>
<div class="container" style="background-color: #d3d3d3;">
    <h2 class="alt">Your browser is pretty old.</h2>

    <p>Unfortunately, we've stopped supporting this browser so that we can focus our energy on
        users with a more modern browser. A newer browser is faster, more secure and
        makes the Web more interesting for all of us.</p>

    <p class="bottom">If you continue using this browser, CourtListener may not work well for you and
        you'll continue seeing this warning. Please upgrade Internet Explorer to one of the two latest versions
        or install and use one of the following <strong>FREE</strong> options before you continue:</p>
    <ul>
        <li><a href="http://getfirefox.com" target="_top">Mozilla Firefox</a></li>
        <li><a href="https://www.google.com/chrome" target="_top">Google Chrome</a></li>
    </ul>
</div>
</body>
</html>

cl/simple_pages/templates/contact_form.html
{% extends "base.html" %}
{% load honeypot %}

{% block title %}Contact Us – CourtListener.com{% endblock %}

{% block search-form %}{% endblock %}

{% block sidebar %}{% endblock %}

{% block content %}
    <div class="col-sm-9 col-md-6 col-sm-push-3" id="sidebar">
        <h2>Contact Us</h2>

        {% if form.errors %}
            <div class="alert alert-danger">
                <p class="bottom">There were errors with your submission.</p>
            </div>
        {% endif %}

        <form action="" method="post">{% csrf_token %}
            {% render_honeypot_field "skip_me_if_alive" %}
            <div class="form-group">
                <label for="id_name">Name</label>
                {{ form.name }}
                {% if form.name.errors %}
                    <p class="help-block">
                        {% for error in form.name.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </p>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="id_email">Email (optional)</label>
                {{ form.email }}
                {% if form.email.errors %}
                    <p class="help-block">
                        {% for error in form.email.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </p>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="id_subject">Subject</label>
                {{ form.subject }}
                {% if form.subject.errors %}
                    <p class="help-block">
                        {% for error in form.subject.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </p>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="id_message">Message</label>
                {{ form.message }}
                {% if form.message.errors %}
                    <p class="help-block">
                        {% for error in form.message.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </p>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary btn-lg pull-right">Send Message</button>
        </form>
    </div>


    <div class="col-sm-3 col-sm-pull-9 col-md-pull-6">
        <h3 class="bottom">Removal Requests</h3>

        <p>If you are concerned about your case appearing on this site,
            please see our <a href="/removal/">removal policy</a>. If,
            after reviewing the policy, you wish to request that we ask
            search engines to remove a document from their results,
            then you must provide us with the specific web address (URL)
            of the document.</p>
        <br>

        <h3 class="bottom">Twitter</h3>

        <p>For quick updates and announcements, follow <a
                href="https://twitter.com/courtlistener">@courtlistener</a> on
            Twitter.</p>
        <br>

        <h3 class="bottom">Blog</h3>

        <p>Follow <a href="https://free.law">The Free Law Blog</a>
            to see our latest announcements and press releases.</p>
        <br>

        <h3 class="bottom">Discussion Forum</h3>

        <p>To talk about CourtListener <a
                href="http://lists.freelawproject.org/cgi-bin/mailman/listinfo/dev">visit
            our forum</a>
            where you can discus the site with others.</p>
        <br>
    </div>
    <div class="col-sm-3"></div>
{% endblock %}

cl/simple_pages/templates/contact_thanks.html
{% extends "base.html" %}

{% block title %}Thank You for Your Message – CourtListener.com{% endblock %}
{% block sidebar %}{% endblock %}
{% block search-form %}{% endblock %}

{% block content %}
    <div class="col-xs-1 col-sm-2 col-md-3"></div>
    <div class="col-xs-10 col-sm-8 col-md-6 well">
        <h2 class="text-center v-offset-below-2">Thank You for Your Message</h2>
        <p>Thanks for the feedback. We appreciate every message we receive and we'll get back to you as soon as we can &mdash; Usually within a few days.
        </p>
    </div>
    <div class="col-xs-1 col-sm-2 col-med-3"></div>
{% endblock %}

cl/simple_pages/templates/honeypot_error.html
{% extends "base.html" %}

{% block head %}
    <meta name="robots" content="noindex, noodp, noarchive, noimageindex"/>
{% endblock %}

{% block privacy %}{% endblock %}

{% block title %}Server Error 400 – CourtListener.com{% endblock %}
{% block sidebar %}{% endblock %}
{% block search-form %}{% endblock %}

{% block content %}
    <div class="col-xs-1 col-sm-2 col-md-3"></div>
    <div class="col-xs-10 col-sm-8 col-md-6 well">
        <h2>400 Bad Request</h2>
        <p>Honey Pot Error: ({{fieldname}}). Request aborted.</p>
        <p>We believe that you're a spam bot, but if you're a human reading
            this we definitely made a mistake. The following may help:</p>
        <ul>
            <li>Try filling out the form on the previous page more carefully,
                or disabling any browser extensions that interact with forms.
            </li>
            <li><a href="{% url "contact" %}">Let us</a> know that you're having trouble using this form.</li>
        </ul>

        <p>Sorry about this. If you continue having problems, please do <a href="{% url "contact" %}">let us know</a>.</p>
    </div>
    <div class="col-xs-1 col-sm-2 col-med-3"></div>
{% endblock %}

cl/simple_pages/templates/maintenance.html
{% extends "base.html" %}

{% block title %}Under maintenance – CourtListener.com{% endblock %}

{% block search-form %}{% endblock %}
{% block sidebar %}{% endblock %}

{% block content %}
    <div class="col-sm-3">&nbsp;</div>
    <div class="col-sm-6">
        <h1><i class="fa fa-wrench gray"></i> CourtListener is currently
            undergoing maintenance.</h1>
        <p>We apologize for the inconvenience, but CourtListener is getting a
        scheduled upgrade. We hope to be done soon.</p>
        <p>You can monitor our progress in <a href="https://twitter.com/#!/courtlistener">
        our twitter stream</a>.</p>
        <p>If you want something to read while you wait for things to come back
            up, perhaps you'll find something interesting on the <a
                    href="https://free.law">Free Law Project
                homepage</a>.
        </p>
    </div>
    <div class="col-sm-3">&nbsp;</div>
{% endblock %}