cl/alerts/urls.py
from django.conf.urls import url
from cl.alerts.views import (
    delete_alert,
    delete_alert_confirm,
    edit_alert_redirect,
)

urlpatterns = [
    url(r'^alert/edit/(\d{1,6})/$', edit_alert_redirect),
    url(r'^alert/delete/(\d{1,6})/$', delete_alert),
    url(r'^alert/delete/confirm/(\d{1,6})/$', delete_alert_confirm),
]

cl/api/urls.py
from cl.api import views
from cl.audio import api_views as audio_views
from cl.people_db import api_views as judge_views
from cl.search import api_views as search_views

from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
# Search & Audio
router.register(r'dockets', search_views.DocketViewSet)
router.register(r'courts', search_views.CourtViewSet)
router.register(r'audio', audio_views.AudioViewSet)
router.register(r'clusters', search_views.OpinionClusterViewSet)
router.register(r'opinions', search_views.OpinionViewSet)
router.register(r'opinions-cited', search_views.OpinionsCitedViewSet)
router.register(r'search', search_views.SearchViewSet, base_name='search')

# Judges
router.register(r'people', judge_views.PersonViewSet)
router.register(r'positions', judge_views.PositionViewSet)
router.register(r'retention-events', judge_views.RetentionEventViewSet)
router.register(r'educations', judge_views.EducationViewSet)
router.register(r'schools', judge_views.SchoolViewSet)
router.register(r'political-affiliations',
                judge_views.PoliticalAffiliationViewSet)
router.register(r'sources', judge_views.SourceViewSet)
router.register(r'aba-ratings', judge_views.ABARatingViewSet)


urlpatterns = [
    url(r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/rest/(?P<version>[v3]+)/', include(router.urls)),

    # Documentation
    url(r'^api/$',
        views.api_index,
        name='api_index'),
    url(r'^api/jurisdictions/$',
        views.court_index,
        name='court_index'),
    url(r'^api/rest-info/(?P<version>v[123])?/?$',
        views.rest_docs,
        name='rest_docs'),
    url(r'^api/bulk-info/$',
        views.bulk_data_index,
        name='bulk_data_index'),
    url(r'^api/rest/v(?P<version>[123])/coverage/(?P<court>.+)/$',
        views.coverage_data,
        name='coverage_data'),

    # Pagerank file
    url(r'^api/bulk/external_pagerank/$',
        views.serve_pagerank_file,
        name='pagerank_file'),

    # Deprecation Dates:
    # v1: 2016-04-01
    # v2: 2016-04-01
    url(r'^api/rest/v(?P<v>[12])/.*',
        views.deprecated_api,
        name='deprecated_api'),
]

cl/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from cl.opinion_page.views import (
    redirect_opinion_pages, redirect_cited_by_feeds,
    redirect_cited_by_page)
#from cl.simple_pages.views import show_maintenance_warning
from cl.sitemap import index_sitemap_maker

urlpatterns = [
    # Admin docs and site
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # Maintenance and SOPA/PIPA mode! Must be here so it intercepts any other
    # urls.
    #url(r'/*', show_maintenance_warning),

    url('', include('cl.audio.urls')),
    url('', include('cl.opinion_page.urls')),
    url('', include('cl.simple_pages.urls')),
    url('', include('cl.users.urls')),
    url('', include('cl.favorites.urls')),
    url('', include('cl.people_db.urls')),
    url('', include('cl.search.urls')),
    url('', include('cl.alerts.urls')),
    url('', include('cl.api.urls')),
    url('', include('cl.donate.urls')),
    url('', include('cl.visualizations.urls')),

    # Sitemaps
    url(r'^sitemap\.xml$', index_sitemap_maker),

    # Redirects
    url(r'^privacy/$', RedirectView.as_view(
        url='/terms/#privacy',
        permanent=True,
    )),
    url(r'^removal/$', RedirectView.as_view(
        url='/terms/#removal',
        permanent=True,
    )),
    url(r'^report/2010/$', RedirectView.as_view(
        url='https://www.ischool.berkeley.edu/files/student_projects/Final_Report_Michael_Lissner_2010-05-07_2.pdf',
        permanent=True,
    )),
    url(r'^report/2012/$', RedirectView.as_view(
        url='https://www.ischool.berkeley.edu/files/student_projects/mcdonald_rustad_report.pdf',
        permanent=True,
    )),
    url(r'report/2013/$', RedirectView.as_view(
        url='https://github.com/freelawproject/related-literature/raw/master/CourtListener%20Studies/Sarah%20Tyler/sarah_tyler_dissertation.pdf',
        permanent=True,
    )),

    # Court stripped from the URL on 2014-09-30.
    # cited-by pages and feeds moved to search results on 2015-08-25
    url(r'^feed/(.*)/cited-by/$', redirect_cited_by_feeds),
    # catch the formats:
    #    /$court/$ascii/$slug/cited-by/ and
    #    /$opinion/$number/$slug/cited-by/
    url(r'^(?:\w{1,15})/(.*)/(?:.*)/cited-by/$', redirect_cited_by_page),
    url(r'^(?:\w{1,15})/(.*)/(.*)/authorities/$', redirect_opinion_pages),
    url(r'^(?:\w{1,15})/(.*)/(.*)/$', redirect_opinion_pages),
]

cl/users/urls.py
from cl.lib.AuthenticationBackend import ConfirmedEmailAuthenticationForm
from cl.users.forms import (
    CustomPasswordResetForm, CustomSetPasswordForm,
)
from cl.users import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views


urlpatterns = [
    # Sign in/out and password pages
    url(
        r'^sign-in/$',
        auth_views.login,
        {
            'template_name': 'register/login.html',
            'authentication_form': ConfirmedEmailAuthenticationForm,
            'extra_context': {'private': False}
        },
        name="sign-in"),
    url(
        r'^sign-out/$',
        auth_views.logout,
        {
            'template_name': 'register/logged_out.html',
            'extra_context': {'private': False}
        },
    ),
    url(
        r'^reset-password/$',
        auth_views.password_reset,
        {
            'template_name': 'register/password_reset_form.html',
            'email_template_name': 'register/password_reset_email.html',
            'extra_context': {'private': False},
            'password_reset_form': CustomPasswordResetForm
        },
        name='password_reset',
    ),
    url(
        r'^reset-password/instructions-sent/$',
        auth_views.password_reset_done,
        {
            'template_name': 'register/password_reset_done.html',
            'extra_context': {'private': True}
        },
        name='password_reset_done',
    ),
    url(
        r'^confirm-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        {
            'template_name': 'register/password_reset_confirm.html',
            'set_password_form': CustomSetPasswordForm,
            'extra_context': {'private': True}
        },
        name='confirm_password',
    ),
    url(
        r'^reset-password/complete/$',
        auth_views.password_reset_complete,
        {
            'template_name': 'register/password_reset_complete.html',
            'extra_context': {'private': True}
        },
        name='password_reset_complete',
    ),

    # Profile pages
    url(
        r'^profile/settings/$',
        views.view_settings,
        name='view_settings'
    ),
    url(r'^profile/favorites/$', views.view_favorites, name='profile_favorites'),
    url(r'^profile/alerts/$', views.view_alerts, name='profile_alerts'),
    url(
        r'^profile/visualizations/$',
        views.view_visualizations,
        name='view_visualizations'
    ),
    url(
        r'^profile/visualizations/deleted/$',
        views.view_deleted_visualizations,
        name='view_deleted_visualizations',
    ),
    url(
        r'^profile/api/$',
        views.view_api,
        name='view_api'
    ),
    url(
        r'^profile/password/change/$',
        views.password_change,
        name='password_change',
    ),
    url(
        r'^profile/delete/$',
        views.delete_account
    ),
    url(
        r'^profile/delete/done/$',
        views.delete_profile_done,
        name='delete_profile_done',
    ),
    url(
        r'^register/$',
        views.register,
        name="register"
    ),
    url(
        r'^register/success/$',
        views.register_success,
        name='register_success',
    ),

    # Registration pages
    url(
        r'^email/confirm/([0-9a-f]{40})/$',
        views.confirm_email,
        name='email_confirm',
    ),
    url(
        r'^email-confirmation/request/$',
        views.request_email_confirmation,
        name='email_confirmation_request'
    ),
    url(
        r'^email-confirmation/success/$',
        views.email_confirm_success,
        name='email_confirm_success'
    ),
]

cl/alerts/models.py
from django.contrib.auth.models import User
from django.db import models

FREQUENCY = (
    ('rt',  'Real Time'),
    ('dly', 'Daily'),
    ('wly', 'Weekly'),
    ('mly', 'Monthly'),
    ('off', 'Off'),
)

ITEM_TYPES = (
    ('o', 'Opinion'),
    ('oa', 'Oral Argument'),
)


class Alert(models.Model):
    user = models.ForeignKey(
        User,
        help_text="The user that created the item",
        related_name="alerts",
    )
    date_created = models.DateTimeField(
        help_text="The time when this item was created",
        auto_now_add=True,
        db_index=True,
    )
    date_modified = models.DateTimeField(
        help_text="The last moment when the item was modified. A value in year"
                  " 1750 indicates the value is unknown",
        auto_now=True,
        db_index=True,
    )
    date_last_hit = models.DateTimeField(
        verbose_name='time of last trigger',
        blank=True,
        null=True
    )
    name = models.CharField(
        verbose_name='a name for the alert',
        max_length=75
    )
    query = models.CharField(
        verbose_name='the text of an alert created by a user',
        max_length=2500
    )
    rate = models.CharField(
        verbose_name='the rate chosen by the user for the alert',
        choices=FREQUENCY,
        max_length=10
    )
    always_send_email = models.BooleanField(
        verbose_name='Always send an alert?',
        default=False
    )

    def __unicode__(self):
        return u'Alert %s: %s' % (self.pk, self.name)

    class Meta:
        ordering = ['rate', 'query']


class RealTimeQueue(models.Model):
    date_modified = models.DateTimeField(
        help_text='the last moment when the item was modified',
        auto_now=True,
        db_index=True,
    )
    item_type = models.CharField(
        help_text='the type of item this is, one of: %s' %
                  ', '.join(['%s (%s)' % (t[0], t[1]) for t in ITEM_TYPES]),
        max_length=3,
        choices=ITEM_TYPES,
        db_index=True,
    )
    item_pk = models.IntegerField(
        help_text='the pk of the item',
    )

cl/api/models.py
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

cl/favorites/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator
from django.db import models
from cl.audio.models import Audio
from cl.search.models import OpinionCluster


class Favorite(models.Model):
    user = models.ForeignKey(
        User,
        help_text="The user that owns the favorite",
        related_name="favorites",
    )
    cluster_id = models.ForeignKey(
        OpinionCluster,
        verbose_name='the opinion cluster that is favorited',
        null=True,
        blank=True,
    )
    audio_id = models.ForeignKey(
        Audio,
        verbose_name='the audio file that is favorited',
        null=True,
        blank=True,
    )
    date_created = models.DateTimeField(
        help_text="The original creation date for the item",
        auto_now_add=True,
        db_index=True
    )
    date_modified = models.DateTimeField(
        auto_now=True,
        db_index=True,
        null=True,
    )
    name = models.CharField(
        'a name for the alert',
        max_length=100,
    )
    notes = models.TextField(
        'notes about the favorite',
        validators=[MaxLengthValidator(500)],
        max_length=500,
        blank=True
    )

    class Meta:
        unique_together = (
            ('cluster_id', 'user'),
            ('audio_id', 'user'),
        )

    def __unicode__(self):
        return u'Favorite %s' % self.id

cl/users/models.py
from datetime import timedelta
from decimal import Decimal
from django.db.models import Sum
from django.utils.timezone import now
from django.db import models
from django.contrib.auth.models import User
from localflavor.us import models as local_models

donation_exclusion_codes = [
    1,  # Unknown error
    3,  # Cancelled
    6,  # Failed
    7,  # Reclaimed/Refunded
]


class BarMembership(models.Model):
    barMembership = local_models.USStateField(
        'the two letter state abbreviation of a bar membership'
    )

    def __unicode__(self):
        return self.get_barMembership_display()

    class Meta:
        verbose_name = 'bar membership'
        ordering = ['barMembership']


class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        related_name='profile',
        verbose_name='the user this model extends',
        unique=True,
    )
    barmembership = models.ManyToManyField(
        BarMembership,
        verbose_name='the bar memberships held by the user',
        blank=True,
    )
    stub_account = models.BooleanField(
        default=False,
    )
    employer = models.CharField(
        "the user's employer",
        max_length=100,
        blank=True,
        null=True,
    )
    address1 = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )
    address2 = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )
    city = models.CharField(
        max_length=50,
        blank=True,
        null=True,
    )
    state = models.CharField(
        max_length=2,
        blank=True,
        null=True,
    )
    zip_code = models.CharField(
        max_length=10,
        blank=True,
        null=True,
    )
    avatar = models.ImageField(
        'the user\'s avatar',
        upload_to='avatars/%Y/%m/%d',
        blank=True,
    )
    wants_newsletter = models.BooleanField(
        'This user wants newsletters',
        default=False,
    )
    plaintext_preferred = models.BooleanField(
        'should the alert should be sent in plaintext',
        default=False,
    )
    activation_key = models.CharField(
        max_length=40,
    )
    key_expires = models.DateTimeField(
        'The time and date when the user\'s activation_key expires',
        blank=True,
        null=True,
    )
    email_confirmed = models.BooleanField(
        'The user has confirmed their email address',
        default=False,
    )

    @property
    def total_donated_last_year(self):
        one_year_ago = now() - timedelta(days=365)
        total = self.user.donations.filter(
            date_created__gte=one_year_ago,
        ).exclude(
            status__in=donation_exclusion_codes,
        ).aggregate(Sum('amount'))['amount__sum']
        if total is None:
            total = Decimal(0.0)
        return total

    @property
    def total_donated(self):
        total = self.user.donations.exclude(
            status__in=donation_exclusion_codes
        ).aggregate(Sum('amount'))['amount__sum']
        if total is None:
            total = Decimal(0.0)
        return total

    def __unicode__(self):
        return u"{name}".format(name=self.user.username)

    class Meta:
        verbose_name = 'user profile'
        verbose_name_plural = 'user profiles'

cl/alerts/views.py
from cl.alerts.models import Alert

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext


@login_required
def edit_alert_redirect(request, alert_id):
    """Note that this method is still very useful because it gives people an
    opportunity to login if they come to the site via one of our email alerts.
    """
    try:
        alert_id = int(alert_id)
    except ValueError:
        return HttpResponseRedirect('/')

    # check if the user can edit this, or if they are url hacking
    alert = get_object_or_404(
        Alert,
        pk=alert_id,
        user=request.user
    )
    return HttpResponseRedirect('/?%s&edit_alert=%s' % (alert.query, alert.pk))


@login_required
def delete_alert(request, pk):
    try:
        pk = int(pk)
    except ValueError:
        return HttpResponseRedirect('/')

    # check if the user can edit this, or if they are url hacking
    alert = get_object_or_404(Alert, pk=pk, user=request.user)

    # if they've made it this far, they have permission to edit the alert
    alert.delete()
    messages.add_message(
        request,
        messages.SUCCESS,
        'Your alert was deleted successfully.'
    )
    return HttpResponseRedirect(reverse("profile_alerts"))


@login_required
def delete_alert_confirm(request, alert_id):
    try:
        alert_id = int(alert_id)
    except ValueError:
        return HttpResponseRedirect('/')
    return render_to_response('delete_confirm.html',
                              {'alert_id': alert_id, 'private': False},
                              RequestContext(request))

cl/users/templates/profile/api.html
{% extends "profile/nav.html" %}
{% block title %}API &ndash; CourtListener.com{% endblock %}

{% block search-form %}{% endblock %}

{% block nav-api %}active{% endblock %}

{% block content %}
    <div class="col-sm-3"></div>
    <div class="col-xs-12 col-sm-6">
        <h3>CourtListener API</h3>
        <p>The CourtListener API is a powerful, first-of-its-kind tool that programmers can use to access the contents of the CourtListener database.
        </p>
        <p>By allowing programmers to access this data, we hope to fulfill our mission of stimulating legal innovation.
        </p>
        <h3>Your API Token</h3>
        <p>To get started, you need an API token. Yours is:</p>
        <h4><code>{{ user.auth_token }}</code></h4>
        <p class="v-offset-above-3"><a href="{% url "api_index" %}" class="btn btn-primary btn-lg">Read the Documentation</a></p>
    </div>
    <div class="col-sm-3"></div>
{% endblock %}

cl/users/templates/profile/favorites.html
{% extends "profile/nav.html" %}

{% block title %}Favorites – CourtListener.com{% endblock %}
{% block search-form %}{% endblock %}

{% block nav-favorites %}active{% endblock %}
{% block footer-scripts %}
    <script defer type="text/javascript"
            src="{{ STATIC_URL }}js/save-favorites.js"></script>
    <script defer type="text/javascript"
            src="{{ STATIC_URL }}js/jquery.NobleCount.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $(".edit-favorite-trigger").click(function (event) {
                event.preventDefault();
                var pk = $(this).data("id");
                var ds = $("#data-store-" + pk);
                $("#id_cluster_id").val(ds.data("cluster_id"));
                $("#id_audio_id").val(ds.data("audio_id"));
                $("#save-favorite-notes-field").val(ds.data("notes"));
                $("#save-favorite-name-field").val(ds.data("name"));
                $("#modal-save-favorite").data("id", pk);
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="col-xs-12">
        {% if user.favorites.all %}
            <div class="table-responsive">
                <table class="table settings-table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th colspan="2">Notes</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for favorite_form in favorite_forms %}
                            <tr id="favorite-row-{{ favorite_form.instance.id }}">
                                <td id="name-{{ favorite_form.instance.id }}">
                                    {% if favorite_form.instance.cluster_id %}
                                        <i class="fa-file-text-o fa gray" title="Opinion"></i>
                                        <a href="{{ favorite_form.instance.cluster_id.get_absolute_url }}">
                                            {{favorite_form.instance.name }}
                                        </a>
                                    {% else %}
                                        <i class="fa-volume-up fa grey" title="Oral Argument"></i>
                                        <a href="{{ favorite_form.instance.audio_id.get_absolute_url }}">
                                            {{ favorite_form.instance.name }}
                                        </a>
                                    {% endif %}
                                </td>
                                <td id="notes-{{ favorite_form.instance.id }}">
                                    {{ favorite_form.instance.notes|default:"(none)" }}
                                </td>
                                <td class="align-top">
                                    <div data-toggle="modal"
                                         data-target="#modal-save-favorite">
                                        <a class="inline edit-favorite-trigger nowrap cursor"
                                           data-id="{{ favorite_form.instance.id }}">Edit / Delete
                                           <i class="fa fa-pencil gray"></i>
                                        </a>

                                        <div id="data-store-{{ favorite_form.instance.id }}"
                                             class="hidden"
                                             data-cluster_id="{{ favorite_form.instance.cluster_id.pk|default_if_none:"" }}"
                                             data-audio_id="{{ favorite_form.instance.audio_id.pk|default_if_none:"" }}"
                                             data-name="{{ favorite_form.instance.name|default_if_none:"" }}"
                                             data-notes="{{ favorite_form.instance.notes|default_if_none:"" }}">
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}

                       {# modal & data storage #}
                       {% include "includes/favorites_modal.html" with favorite_form=blank_favorite_form edit=True%}
                    </tbody>
                </table>
            </div>
        {% else %}
            <div class="row">
                <div class="col-sm-12">
                    <h3>You Have Not Saved Any Favorites</h3>
                    <p>To save a favorite, click the star icon next to a
                        document's title, give it a title and make a note.</p>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

cl/users/templates/profile/settings.html
{% extends "profile/nav.html" %}

{% block title %}Account Settings – CourtListener.com{% endblock %}
{% block search-form %}{% endblock %}

{% block nav-account %}active{% endblock %}

{% block content %}
    <div class="col-xs-12">
        {% if user_form.errors or profile_form.errors %}
            <div class="alert alert-danger">
                <p class="bottom">There were errors with your submission.</p>
            </div>
        {% endif %}
    </div>

    <div class="col-sm-3"></div>
    <div class="col-xs-12 col-sm-6">
        <form action="" method="post">{% csrf_token %}
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="id_first_name">First Name</label>
                        {{ user_form.first_name }}
                        {% if user_form.first_name.errors %}
                            <p class="help-block">
                                {% for error in user_form.first_name.errors %}
                                    {{ error|escape }}
                                {% endfor %}
                            </p>
                        {% endif %}
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="id_last_name">Last Name</label>
                        {{ user_form.last_name }}
                        {% if user_form.last_name.errors %}
                            <p class="help-block">
                                {% for error in user_form.last_name.errors %}
                                    {{ error|escape }}
                                {% endfor %}
                            </p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="id_email">Email (will log you out until re-confirmed)*</label>
                {{ user_form.email }}
                {% if user_form.email.errors %}
                    <p class="form-control">
                        {% for error in user_form.email.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_employer">Employer</label>
                {{ profile_form.employer }}
                {% if profile_form.employer.errors %}
                    <p class="form-control">
                        {% for error in profile_form.employer.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_barmembership">Bar Memberships (hold control to select more than one)</label>
                {{ profile_form.barmembership }}
                {% if profile_form.barmembership.errors %}
                    <p class="form-control">
                        {% for error in profile_form.barmembership.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_address1">Mailing Address 1</label>
                {{ profile_form.address1 }}
                {% if profile_form.address1.errors %}
                    <p class="help-block">
                        {% for error in profile_form.address1.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_address2">Mailing Address 2</label>
                {{ profile_form.address2 }}
                {% if profile_form.address1.errors %}
                    <p class="help-block">
                        {% for error in profile_form.address2.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_city">City</label>
                {{ profile_form.city }}
                {% if profile_form.city.errors %}
                    <p class="help-block">
                        {% for error in profile_form.city.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </p>
                {% endif %}
            </div>
            <div class="row">
                <div class="col-sm-7">
                    <div class="form-group">
                        <label for="id_state">State</label>
                        {{ profile_form.state }}
                        {% if profile_form.state.errors %}
                            <span class="help-block">
                                {% for error in profile_form.state.errors %}
                                    {{ error|escape }}
                                {% endfor %}
                            </span>
                        {% endif %}
                    </div>
                </div>
                <div class="col-sm-5">
                    <div class="form-group">
                        <label for="id_zip_code">Zip</label>
                        {{ profile_form.zip_code }}
                        {% if profile_form.zip_code.errors %}
                            <p class="help-block">
                                {% for error in profile_form.zip_code.errors %}
                                    {{ error|escape }}
                                {% endfor %}
                            </p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="id_plaintext_preferred">
                    {{ profile_form.plaintext_preferred }}
                    I prefer plain text emails</label>
                {% if profile_form.plaintext_preferred.errors %}
                    <p class="help-block">
                        {% for error in profile_form.plaintext_preferred.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </p>
                {% endif %}
            </div>
            <div class="form-group v-offset-below-4">
                <label for="id_wants_newsletter">
                    {{ profile_form.wants_newsletter }}
                    Send me the monthly newsletter</label>
                {% if profile_form.wants_newsletter.errors %}
                    <p class="help-block">
                        {% for error in profile_form.wants_newsletter.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </p>
                {% endif %}
            </div>
            <input type="hidden" value="{{user.username}}" name="user" id="id_user">
            <button type="submit" class="btn btn-primary float-right">Save Changes</button>
            <a href="/profile/delete">Delete My Account&hellip;</a>
        </form>
    </div>
    <div class="col-sm-3"></div>
{% endblock %}